spring.datasource.url=jdbc:postgresql://localhost:5432/pessoa_db
spring.datasource.username=postgres
spring.datasource.password=0322
spring.datasource.driver-class-name=org.postgresql.Driver

# Em desenvolvimento pode deixar update; se quiser travar o schema, use validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
